# Generated by Django 5.0.3 on 2024-08-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_delete_leaderoard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-completed_at', '-started_at']},
        ),
    ]
