# Generated by Django 5.0.3 on 2024-08-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_useraccount_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
